---

- name: Configure console permissions
  ansible.builtin.template:
    src: template.perms.j2
    dest: "{{ console_perms_file.path }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  loop: "{{ console_perms_to_manage }}"
  loop_control:
    loop_var: console_perms_file
    label: "{{ console_perms_file.path }}"
  vars:
    console_perms_to_manage: >-
      {{ console_perms
         + ((console_perms_load_from_hostvars)
            | ternary(console_perms
                      | default([])
                      | flatten,
                      [])) }}
  tags:
    - role::console_perms
