---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  export ANSIBLE_ACTION_PLUGINS=$PWD/action_plugins
  export ANSIBLE_BECOME_PLUGINS=$PWD/become_plugins
  export ANSIBLE_CACHE_PLUGINS=$PWD/cache_plugins
  export ANSIBLE_CALLBACK_PLUGINS=$PWD/callback_plugins
  export ANSIBLE_CLICONF_PLUGINS=$PWD/cliconf_plugins
  export ANSIBLE_CONNECTION_PLUGINS=$PWD/connection_plugins
  export ANSIBLE_DOC_FRAGMENT_PLUGINS=$PWD/doc_fragment_plugins
  export ANSIBLE_FILTER_PLUGINS=$PWD/filter_plugins
  export ANSIBLE_HTTPAPI_PLUGINS=$PWD/httpapi_plugins
  export ANSIBLE_INVENTORY_PLUGINS=$PWD/inventory_plugins
  export ANSIBLE_LIBRARY=$PWD/library
  export ANSIBLE_LOOKUP_PLUGINS=$PWD/lookup_plugins
  export ANSIBLE_NETCONF_PLUGINS=$PWD/netconf_plugins
  export ANSIBLE_STRATEGY_PLUGINS=$PWD/strategy_plugins
  export ANSIBLE_TERMINAL_PLUGINS=$PWD/terminal_plugins
  export ANSIBLE_TEST_PLUGINS=$PWD/test_plugins
  export ANSIBLE_VARS_PLUGINS=$PWD/vars_plugins
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: centos:6
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "fedora29-${INSTANCE_UUID:-1}"
    image: fedora:29
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_29
  - name: "fedora30-${INSTANCE_UUID:-1}"
    image: fedora:30
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_30
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          console_perms_load_from_hostvars: yes
          console_perms:
            - path: /etc/security/console.perms
              classes:
                - name: console
                  files:
                    - tty[0-9][0-9]*
                    - vc/[0-9][0-9]*
                    - :[0-9]+\.[0-9]+
                    - :[0-9]+
                - name: xconsole
                  files:
                    - :[0-9]+\.[0-9]+
                    - :[0-9]+
            - path: /etc/security/console.perms.d/51-default.perms
              classes:
                - name: floppy
                  files:
                    - /dev/fd[0-1]*
                    - /dev/floppy/*
                    - /mnt/floppy*
                - name: sound
                  files:
                    - /dev/dsp*
                    - /dev/audio*
                    - /dev/midi*
                    - /dev/mixer*
                    - /dev/sequencer
                    - /dev/sound/*
                    - /dev/beep
                    - /dev/snd/*
                - name: cdrom
                  files:
                    - /dev/cdrom*
                    - /dev/cdroms/*
                    - /dev/cdwriter*
                    - /mnt/cdrom*
                - name: scanner
                  files:
                    - /dev/scanner
                    - /dev/usb/scanner*
              permissions:
                - class: <console>
                  class_perm: "0660"
                  device: <floppy>
                  revert_mode: "0660"
                  revert_owner: root
                  revert_group: floppy
                - class: <console>
                  class_perm: "0660"
                  device: <sound>
                  revert_mode: '0640'
                  revert_owner: root
                - class: <console>
                  class_perm: "0660"
                  device: <cdrom>
                  revert_mode: "0660"
                  revert_owner: root
                  revert_group: disk
          console_perms_extra:
            - path: /etc/security/console.perms.d/55-default.perms
              classes:
                - name: transducer
                  files:
                    - /dev/transducer/*
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
