---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos6
    dockerfile: Dockerfile.centos6.j2
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:stream8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: quay.io/fedora/fedora:34
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
  - name: "fedora35-${INSTANCE_UUID:-1}"
    image: quay.io/fedora/fedora:35
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_35
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          console_perms_load_from_hostvars: yes
          console_perms:
            - path: /etc/security/console.perms
              classes:
                - name: console
                  files:
                    - tty[0-9][0-9]*
                    - vc/[0-9][0-9]*
                    - :[0-9]+\.[0-9]+
                    - :[0-9]+
                - name: xconsole
                  files:
                    - :[0-9]+\.[0-9]+
                    - :[0-9]+
            - path: /etc/security/console.perms.d/51-default.perms
              classes:
                - name: floppy
                  files:
                    - /dev/fd[0-1]*
                    - /dev/floppy/*
                    - /mnt/floppy*
                - name: sound
                  files:
                    - /dev/dsp*
                    - /dev/audio*
                    - /dev/midi*
                    - /dev/mixer*
                    - /dev/sequencer
                    - /dev/sound/*
                    - /dev/beep
                    - /dev/snd/*
                - name: cdrom
                  files:
                    - /dev/cdrom*
                    - /dev/cdroms/*
                    - /dev/cdwriter*
                    - /mnt/cdrom*
                - name: scanner
                  files:
                    - /dev/scanner
                    - /dev/usb/scanner*
              permissions:
                - class: <console>
                  class_perm: "0660"
                  device: <floppy>
                  revert_mode: "0660"
                  revert_owner: root
                  revert_group: floppy
                - class: <console>
                  class_perm: "0660"
                  device: <sound>
                  revert_mode: '0640'
                  revert_owner: root
                - class: <console>
                  class_perm: "0660"
                  device: <cdrom>
                  revert_mode: "0660"
                  revert_owner: root
                  revert_group: disk
          console_perms_extra:
            - path: /etc/security/console.perms.d/55-default.perms
              classes:
                - name: transducer
                  files:
                    - /dev/transducer/*
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
